@prefix :  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Crypt-XkcdPassword/project>
	:runtime-requirement  [ :on "perl 5.008"^^:CpanId ];
	:runtime-requirement  [ :on "match::simple"^^:CpanId ];
	:runtime-requirement  [ :on "Module::Runtime"^^:CpanId ];
	:runtime-requirement  [ :on "Moo 1.006000"^^:CpanId ];
	:runtime-requirement  [ :on "Types::Standard 1.000000"^^:CpanId ];
	:test-requirement     [ :on "Test::More 0.96"^^:CpanId ].
