# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Crypt-XkcdPassword/project>
	:perl_version_from _:main;
	:version_from _:main;
	:readme_from _:main;
	:test_requires "Test::More 0.96";
	:requires "match::simple", "Module::Runtime", "Moo", "Role::Commons::Authority", "Types::Standard".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Crypt/XkcdPassword.pm".

